### ISSUE TITLE
AntiSpam don't work in italian

### ISSUE THREAD

**Issue by ghost** [TheHamkerCat/telegram-antispam-rs#3]
Hi. I've checked the antispam and it doesn't works in Italian

Subscribe to my YouTube channel => iscriviti al mio canale YouTube

And it didn't recognize it as spam.

**Comment by TheHamkerCat** [comment]
You need to use an Italian dataset, check dockerfile

**Comment by ghost** [comment]
Can you give me the link of the italian dataset? Maybe you have one?

**Comment by TheHamkerCat** [comment]
I don't have
